version: 2

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
jobs:
  publish:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build and publish images
          command:  ./scripts/publish.sh
